### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [127]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


The above array is an 1D array.

In [128]:
# 2D and 3D

b = np.array([[1,2],[3,4]])
print(b)


[[1 2]
 [3 4]]


In [129]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


1D = vector
2D = matrix
3D = tensor

In [130]:
# dtype
a = np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [131]:
b = np.array([0,1,0],dtype=bool)
b

array([False,  True, False])

In [132]:
c = np.array([4,5j,6],dtype=complex)
c

array([4.+0.j, 0.+5.j, 6.+0.j])

In [133]:
# np.arange
# similar to range of python
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
# with reshape
# reshape will be (row,column)

a = np.arange(1,13).reshape(4,3)
a


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [135]:
# reshape
a = np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [136]:
# np.ones and np.zeros
# ones is used to initialize the array of 1 for deep learning concepts
# zeros is used to initialize the array of 0

a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [137]:
a = np.zeros((4,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [138]:
# np.random
np.random.random((3,4))

array([[0.70527657, 0.28408936, 0.08085878, 0.08591522],
       [0.33743097, 0.34214687, 0.88462734, 0.14678742],
       [0.23330269, 0.35859983, 0.49612541, 0.34689159]])

In [139]:
# np.linspace

a = np.linspace(-11,11,20)
a

array([-11.        ,  -9.84210526,  -8.68421053,  -7.52631579,
        -6.36842105,  -5.21052632,  -4.05263158,  -2.89473684,
        -1.73684211,  -0.57894737,   0.57894737,   1.73684211,
         2.89473684,   4.05263158,   5.21052632,   6.36842105,
         7.52631579,   8.68421053,   9.84210526,  11.        ])

linspace is used in ml for plotting

In [140]:
# np.identity
#  used to create a identity matrix 

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Array Attributes

In [141]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [142]:
# ndim
#  ndim gives no of dimension i.e it is 1D 2D or 3D
a1.ndim


1

In [143]:
a2.ndim

2

In [144]:
a3.ndim

3

In [145]:
# shape
# provides the no of rows and column

print(a1.shape)
a1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [147]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [148]:
# size
#  gives the toatal number of items !
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [149]:
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [150]:
print(a1.size)
a1

10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
# itemsize
a3.itemsize

4

In [152]:
a2.itemsize

8

In [153]:
a1.itemsize

4

In [154]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int32


### Changing Datatype

In [155]:
# astype
# is used to check or reduce the unwanted space taken by the array elements
a3.dtype=np.int64
a3.dtype


dtype('int64')

In [156]:
a3.size

4

In [157]:
a3.astype(np.int32)

array([[[0],
        [2]],

       [[4],
        [6]]])

### Array Operations

In [158]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [159]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [160]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [161]:
# vector operations
# arithmetic
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

### Array Functions

In [162]:
# max/min/sum/prod
# 0 -> col and 1 -> row
a1 = np.arange(1,13).reshape(3,4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [163]:
np.max(a1)

12

In [164]:
np.min(a1)

1

In [165]:
np.sum(a1)

78

In [166]:
np.prod(a1)

479001600

In [167]:
np.min(a1,axis=1)

array([1, 5, 9])

In [168]:
np.min(a1,axis=0)

array([1, 2, 3, 4])

In [169]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[69., 58., 63.],
       [12., 52., 46.],
       [72., 56., 67.]])

In [170]:
np.prod(a1,axis=0)

array([ 59616., 168896., 194166.])

In [171]:
# mean/median/std/var
np.mean(a1)

55.0

In [172]:
np.mean(a1,axis=1)

array([63.33333333, 36.66666667, 65.        ])

In [173]:
np.std(a1)

17.13346303452853

In [174]:
# trigonomoetric functions
np.sin(a1)

array([[-0.11478481,  0.99287265,  0.1673557 ],
       [-0.53657292,  0.98662759,  0.90178835],
       [ 0.25382336, -0.521551  , -0.85551998]])

In [175]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)
print()
np.dot(a2,a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]



array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [176]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [177]:
c = np.arange(4,8).reshape(2,2)
c

array([[4, 5],
       [6, 7]])

In [178]:
np.dot(b,c)

array([[ 6,  7],
       [26, 31]])

In [179]:
# log and exponents
np.log(a1)

array([[4.2341065 , 4.06044301, 4.14313473],
       [2.48490665, 3.95124372, 3.8286414 ],
       [4.27666612, 4.02535169, 4.20469262]])

In [180]:
np.exp(a1)

array([[9.25378173e+29, 1.54553894e+25, 2.29378316e+27],
       [1.62754791e+05, 3.83100800e+22, 9.49611942e+19],
       [1.85867175e+31, 2.09165950e+24, 1.25236317e+29]])

In [181]:
np.random.random((2,3))*100

array([[73.81726849, 94.44786699, 55.86139306],
       [59.15699966, 64.86222349, 60.95204656]])

In [182]:
# round/floor/ceil
np.round((np.random.random((2,3))*100),2)

array([[19.61, 86.76, 94.57],
       [90.5 ,  3.1 , 90.22]])

In [183]:
# backward 0.9 = 1
np.floor((np.random.random((2,3))*100),2)

TypeError: return arrays must be of ArrayType

In [ ]:
#  forward 0.4 = 1
np.ceil((np.random.random((2,3))*100),2)

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[-1]

9

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

6

In [ ]:
a2[2,3]

11

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a3[0,0,0]

0

In [ ]:
a3[0,1,0]

2

In [ ]:
a3[1,1,0]

6

### slicing

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1:2,::3]

array([[4, 7]])

In [ ]:
a2[0:2,1::2]

In [ ]:
a2[::2,1::2]

In [ ]:
a2[1,::3]

In [ ]:
a2[0,:]

In [ ]:
a2[:,2]

In [ ]:
a2[1:,1:3]

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1:2,::,::]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [ ]:
a3[0::2,::,::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0:1,1:2]

array([[[3, 4, 5]]])

In [ ]:
a3[1:2,::,1:2]

array([[[10],
        [13],
        [16]]])

In [ ]:
a3[2:,1::,1::]

array([[[22, 23],
        [25, 26]]])

In [ ]:
a3[0::2,0:1,0::2]

array([[[ 0,  2]],

       [[18, 20]]])

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

In [ ]:
for i in a2:
  print(i)

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
count = 0
for i in a3:
  print(i)
  count = count + 1
  
print(count)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
3


In [ ]:
a3.size

27

In [ ]:
count = 0
for i in np.nditer(a3):
    count += 1
    print(i)
print("count is =",count)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
count is = 27


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
count = 0
for i in np.nditer(a2):
    count += 1
    print(i)
print("count is =",count)

0
1
2
3
4
5
6
7
8
9
10
11
count is = 12


### Reshaping

In [ ]:
# reshape

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
# converts 2d or anyD into 1D
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [184]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [185]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [186]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [187]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting

In [188]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [189]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]