### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np

In [3]:
a = np.random.randint(1,100,15)
a

array([86, 57, 66, 29, 23, 40, 73, 36, 29, 55, 69, 83, 11, 36, 63])

In [4]:
np.sort(a)

array([11, 23, 29, 29, 36, 36, 40, 55, 57, 63, 66, 69, 73, 83, 86])

In [5]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[91, 57, 47,  3],
       [94, 73, 65, 46],
       [32, 49,  3, 92],
       [47, 83, 90, 97],
       [88, 89, 55,  5],
       [59, 84, 46, 15]])

In [6]:
import time as t
start = t.time()
np.sort(b)
print(t.time()-start)

0.0010113716125488281


In [7]:
import time as t
start = t.time()
np.sort(b,kind='heapsort')
print(t.time()-start)

0.001001119613647461


In [8]:
import time as t
start = t.time()
np.sort(b,kind='stablesort')
print(t.time()-start)

0.0010001659393310547


In [9]:
np.sort(a)

array([11, 23, 29, 29, 36, 36, 40, 55, 57, 63, 66, 69, 73, 83, 86])

In [10]:
np.sort(a)[::-1]

array([86, 83, 73, 69, 66, 63, 57, 55, 40, 36, 36, 29, 29, 23, 11])

In [11]:
b

array([[91, 57, 47,  3],
       [94, 73, 65, 46],
       [32, 49,  3, 92],
       [47, 83, 90, 97],
       [88, 89, 55,  5],
       [59, 84, 46, 15]])

In [12]:
np.sort(b,axis=0)

array([[32, 49,  3,  3],
       [47, 57, 46,  5],
       [59, 73, 47, 15],
       [88, 83, 55, 46],
       [91, 84, 65, 92],
       [94, 89, 90, 97]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [13]:
a

array([86, 57, 66, 29, 23, 40, 73, 36, 29, 55, 69, 83, 11, 36, 63])

In [14]:
# code
np.append(a,200)

array([ 86,  57,  66,  29,  23,  40,  73,  36,  29,  55,  69,  83,  11,
        36,  63, 200])

In [15]:
b

array([[91, 57, 47,  3],
       [94, 73, 65, 46],
       [32, 49,  3, 92],
       [47, 83, 90, 97],
       [88, 89, 55,  5],
       [59, 84, 46, 15]])

In [16]:
b.shape

(6, 4)

In [17]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)


array([[91.        , 57.        , 47.        ,  3.        ,  0.41067723],
       [94.        , 73.        , 65.        , 46.        ,  0.9086885 ],
       [32.        , 49.        ,  3.        , 92.        ,  0.45727946],
       [47.        , 83.        , 90.        , 97.        ,  0.47282113],
       [88.        , 89.        , 55.        ,  5.        ,  0.82037063],
       [59.        , 84.        , 46.        , 15.        ,  0.14981509]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [18]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [19]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.vstack((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [22]:
np.hstack((c,d))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [23]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [24]:
u = np.random.randint(1,10,50)
u

array([8, 6, 3, 6, 6, 1, 9, 7, 4, 8, 4, 6, 9, 8, 9, 3, 8, 5, 2, 4, 7, 5,
       8, 2, 6, 2, 5, 5, 4, 8, 8, 6, 9, 2, 6, 1, 9, 4, 7, 7, 2, 2, 2, 8,
       2, 5, 1, 2, 6, 2])

In [25]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [26]:
np.unique(u)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [27]:
a = np.arange(0,15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
# code
a.shape

(15,)

In [29]:
np.expand_dims(a,axis=0).shape


(1, 15)

In [30]:
np.expand_dims(a,axis=1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [31]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [32]:
a = np.random.randint(1,100,15)
a

array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

In [33]:
a[a>50]

array([86, 54, 82, 55, 79])

In [34]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  4,  8, 11], dtype=int64),)

In [35]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 5,  0, 32,  0,  0, 24, 25, 44,  0, 31, 32,  0, 31, 15, 37])

In [36]:
np.where(a%2 == 0,0,a)

array([ 5,  0,  0,  0,  0,  0, 25,  0, 55, 31,  0, 79, 31, 15, 37])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [37]:
# code
a

array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

In [38]:
np.argmax(a)

1

In [39]:
a[5]

24

In [40]:
np.argmin(a)

0

In [41]:
b = np.round(np.random.random(64).reshape(8,8)*100,0)

In [42]:
b

array([[70., 37., 97., 31., 60., 28., 79., 28.],
       [49., 18., 53., 90., 44., 56., 63., 29.],
       [56., 26., 75., 95.,  3., 60., 31., 45.],
       [53.,  2., 12., 36., 44., 86., 90., 19.],
       [25., 53., 50., 50., 59., 91., 38., 94.],
       [ 5., 37., 43., 86., 84.,  5., 69., 58.],
       [ 8., 37., 38., 30.,  7., 82., 82., 72.],
       [57., 96., 62., 13., 88., 88., 68., 23.]])

In [43]:
np.size(b)

64

In [44]:
np.argmax(b,axis=0)

array([0, 7, 0, 2, 7, 4, 3, 4], dtype=int64)

In [45]:
np.argmax(b,axis=1)

array([2, 3, 3, 6, 7, 3, 5, 1], dtype=int64)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [46]:
a

array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

In [47]:
np.cumsum(a)

array([  5,  91, 123, 177, 259, 283, 308, 352, 407, 438, 470, 549, 580,
       595, 632])

In [48]:
b

array([[70., 37., 97., 31., 60., 28., 79., 28.],
       [49., 18., 53., 90., 44., 56., 63., 29.],
       [56., 26., 75., 95.,  3., 60., 31., 45.],
       [53.,  2., 12., 36., 44., 86., 90., 19.],
       [25., 53., 50., 50., 59., 91., 38., 94.],
       [ 5., 37., 43., 86., 84.,  5., 69., 58.],
       [ 8., 37., 38., 30.,  7., 82., 82., 72.],
       [57., 96., 62., 13., 88., 88., 68., 23.]])

In [49]:
np.cumsum(b)

array([  70.,  107.,  204.,  235.,  295.,  323.,  402.,  430.,  479.,
        497.,  550.,  640.,  684.,  740.,  803.,  832.,  888.,  914.,
        989., 1084., 1087., 1147., 1178., 1223., 1276., 1278., 1290.,
       1326., 1370., 1456., 1546., 1565., 1590., 1643., 1693., 1743.,
       1802., 1893., 1931., 2025., 2030., 2067., 2110., 2196., 2280.,
       2285., 2354., 2412., 2420., 2457., 2495., 2525., 2532., 2614.,
       2696., 2768., 2825., 2921., 2983., 2996., 3084., 3172., 3240.,
       3263.])

In [50]:
np.cumsum(b,axis=1)

array([[ 70., 107., 204., 235., 295., 323., 402., 430.],
       [ 49.,  67., 120., 210., 254., 310., 373., 402.],
       [ 56.,  82., 157., 252., 255., 315., 346., 391.],
       [ 53.,  55.,  67., 103., 147., 233., 323., 342.],
       [ 25.,  78., 128., 178., 237., 328., 366., 460.],
       [  5.,  42.,  85., 171., 255., 260., 329., 387.],
       [  8.,  45.,  83., 113., 120., 202., 284., 356.],
       [ 57., 153., 215., 228., 316., 404., 472., 495.]])

In [51]:
np.cumsum(b,axis=0)

array([[ 70.,  37.,  97.,  31.,  60.,  28.,  79.,  28.],
       [119.,  55., 150., 121., 104.,  84., 142.,  57.],
       [175.,  81., 225., 216., 107., 144., 173., 102.],
       [228.,  83., 237., 252., 151., 230., 263., 121.],
       [253., 136., 287., 302., 210., 321., 301., 215.],
       [258., 173., 330., 388., 294., 326., 370., 273.],
       [266., 210., 368., 418., 301., 408., 452., 345.],
       [323., 306., 430., 431., 389., 496., 520., 368.]])

In [52]:
a

array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

In [53]:
# np.cumprod
np.cumprod(a)

array([          5,         430,       13760,      743040,    60929280,
        1462302720, -2097137664, -2079744000,  1578196992,  1679466496,
       -2091646976, -2031353856,  1452539904,   313262080, -1294204928])

In [54]:
b

array([[70., 37., 97., 31., 60., 28., 79., 28.],
       [49., 18., 53., 90., 44., 56., 63., 29.],
       [56., 26., 75., 95.,  3., 60., 31., 45.],
       [53.,  2., 12., 36., 44., 86., 90., 19.],
       [25., 53., 50., 50., 59., 91., 38., 94.],
       [ 5., 37., 43., 86., 84.,  5., 69., 58.],
       [ 8., 37., 38., 30.,  7., 82., 82., 72.],
       [57., 96., 62., 13., 88., 88., 68., 23.]])

In [55]:
np.cumprod(b,axis=1)

array([[7.00000000e+01, 2.59000000e+03, 2.51230000e+05, 7.78813000e+06,
        4.67287800e+08, 1.30840584e+10, 1.03364061e+12, 2.89419372e+13],
       [4.90000000e+01, 8.82000000e+02, 4.67460000e+04, 4.20714000e+06,
        1.85114160e+08, 1.03663930e+10, 6.53082756e+11, 1.89393999e+13],
       [5.60000000e+01, 1.45600000e+03, 1.09200000e+05, 1.03740000e+07,
        3.11220000e+07, 1.86732000e+09, 5.78869200e+10, 2.60491140e+12],
       [5.30000000e+01, 1.06000000e+02, 1.27200000e+03, 4.57920000e+04,
        2.01484800e+06, 1.73276928e+08, 1.55949235e+10, 2.96303547e+11],
       [2.50000000e+01, 1.32500000e+03, 6.62500000e+04, 3.31250000e+06,
        1.95437500e+08, 1.77848125e+10, 6.75822875e+11, 6.35273502e+13],
       [5.00000000e+00, 1.85000000e+02, 7.95500000e+03, 6.84130000e+05,
        5.74669200e+07, 2.87334600e+08, 1.98260874e+10, 1.14991307e+12],
       [8.00000000e+00, 2.96000000e+02, 1.12480000e+04, 3.37440000e+05,
        2.36208000e+06, 1.93690560e+08, 1.58826259e+10, 1.

In [56]:
a

array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [57]:
a

array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

In [58]:
np.percentile(a,50)

32.0

In [59]:
np.percentile(b,30)

35.49999999999999

In [60]:
np.median(a)

32.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [61]:
# code
a

array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

In [62]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 2, 5, 1, 2, 0, 1, 2, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [63]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [64]:
# code
a


array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

isin is used to check multiple items are in the aray or not

In [65]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [66]:
# code
a

array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

In [67]:
b = a[::-1]
b

array([37, 15, 31, 79, 32, 31, 55, 44, 25, 24, 82, 54, 32, 86,  5])

In [68]:
np.flip(a)

array([37, 15, 31, 79, 32, 31, 55, 44, 25, 24, 82, 54, 32, 86,  5])

In [69]:
print(b==np.flip(a))

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]


In [70]:
b = np.random.randint(1,100,25).reshape(5,5)
b

array([[33, 48, 12, 19, 36],
       [37,  3, 68, 85, 18],
       [69, 58, 99, 52, 45],
       [35, 57,  9, 55, 65],
       [80,  8, 15, 86, 97]])

In [71]:
np.flip(b,axis=1)

array([[36, 19, 12, 48, 33],
       [18, 85, 68,  3, 37],
       [45, 52, 99, 58, 69],
       [65, 55,  9, 57, 35],
       [97, 86, 15,  8, 80]])

In [72]:
np.flip(b,axis=0)

array([[80,  8, 15, 86, 97],
       [35, 57,  9, 55, 65],
       [69, 58, 99, 52, 45],
       [37,  3, 68, 85, 18],
       [33, 48, 12, 19, 36]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [73]:
# code
a

array([ 5, 86, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

put can be undestood as replace but multilple items at a time

In [74]:
np.put(a,[0,1],[12,35])
a

array([12, 35, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

delete is used to delete multiple items from the array ..... its just like the list.delete

In [75]:
# code
a

array([12, 35, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

In [76]:
np.delete(a,[0,2,4])

array([35, 54, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [77]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [78]:
np.intersect1d(m,n)

array([3, 4, 5])

In [79]:
np.setdiff1d(n,m)

array([6, 7])

In [80]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [81]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [82]:
# code
a

array([12, 35, 32, 54, 82, 24, 25, 44, 55, 31, 32, 79, 31, 15, 37])

In [83]:
np.clip(a,a_min=25,a_max=75)

array([25, 35, 32, 54, 75, 25, 25, 44, 55, 31, 32, 75, 31, 25, 37])

In [84]:
np.full((2,2),7) 

array([[7, 7],
       [7, 7]])

In [85]:
# 17. np.swapaxes

In [86]:
# 18. np.uniform

In [87]:
# 19. np.count_nonzero

In [88]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [89]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [90]:

# 25. np.allclose and equals